name: Deploy Aurora User Sync Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "user-operations/aurora-user-sync/**"

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  wait-for-terraform:
    name: Wait for Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check and Wait
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=$(gh run list --workflow "Terraform Production" --status in_progress --limit 1 --json databaseId --jq '.[0].databaseId')
          
          if [ "$RUN_ID" != "null" ] && [ -n "$RUN_ID" ]; then
            echo "Terraform is currently running (ID: $RUN_ID). Waiting for it to finish..."
            
            gh run watch $RUN_ID
            
            CONCLUSION=$(gh run view $RUN_ID --json conclusion --jq '.conclusion')
            if [ "$CONCLUSION" != "success" ]; then
              echo "Terraform workflow did not succeed (Status: $CONCLUSION). Aborting deployment."
              exit 1
            fi
            echo "Terraform finished successfully. Proceeding!"
          else
            echo "No Terraform runs in progress. Proceeding with deployment."
          fi

  deploy:
    needs: wait-for-terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: shotrip-prod/shotrip-prod-aurorauser-sync
          IMAGE_TAG: latest
        working-directory: ./user-operations/aurora-user-sync
        run: |
          docker build --provenance=false -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
          --function-name shotrip-prod-aurorauser-sync \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/shotrip-prod/shotrip-prod-aurorauser-sync:latest
