name: "Terraform Production"

on:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: "ap-northeast-1"
      AWS_DEFAULT_REGION: "ap-northeast-1"
      TF_VAR_bastion_allowed_ip: ${{ secrets.BASTION_IP }}

    steps:
      - name: Maximize build space (Swap extension)
        run: |
          sudo swapoff -a || true
          sudo rm -f /swapfile || true
          sudo dd if=/dev/zero of=/swapfile bs=1M count=4096
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./infra/terraform

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        working-directory: ./infra/terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform plan -no-color -out=tfplan > plan_console_output.log
          terraform apply -auto-approve -no-color -parallelism=5 tfplan
        working-directory: ./infra/terraform